/**
 * Generate a MACD-V chart PNG and optionally post to Discord.
 *
 * Usage:
 *   npx tsx scripts/generate-chart.ts BTC-USD 15m        # Save PNG to tmp/
 *   npx tsx scripts/generate-chart.ts BTC-USD 1h discord  # Save + post to Discord
 *
 * Environment:
 *   LIVERMORE_REDIS_URL  - Redis connection (injected via .ps1)
 *   DISCORD_LIVERMORE_BOT - Discord webhook (injected via .ps1, needed for discord mode)
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { validateEnv } from '@livermore/utils';
import { createRedisClient, testRedisConnection, exchangeCandleKey } from '@livermore/cache';
import { CandleSchema, type Candle, type Timeframe } from '@livermore/schemas';
import { generateMacdVChart } from '@livermore/charts';

async function main() {
  const symbol = process.env.CHART_SYMBOL || 'BTC-USD';
  const timeframe = (process.env.CHART_TIMEFRAME || '15m') as Timeframe;
  const postToDiscord = process.env.CHART_DISCORD === 'true';
  const displayBars = parseInt(process.env.CHART_BARS || '60', 10);
  const exchangeId = 1; // Coinbase

  console.log(`Generating chart: ${symbol} ${timeframe} (${displayBars} bars)...`);

  const config = validateEnv();
  const redis = createRedisClient(config);
  await testRedisConnection(redis);

  // Fetch candles — need extra for MACD-V warmup (35 bars minimum)
  const fetchCount = displayBars + 50; // Extra bars for indicator warmup
  const key = exchangeCandleKey(exchangeId, symbol, timeframe);
  const rawCandles = await redis.zrange(key, -fetchCount, -1);

  if (rawCandles.length < 35) {
    console.error(`Insufficient candle data: ${rawCandles.length} candles (need 35+)`);
    await redis.quit();
    process.exit(1);
  }

  const candles: Candle[] = rawCandles.map((json) => CandleSchema.parse(JSON.parse(json)));
  console.log(`Fetched ${candles.length} candles from Redis`);

  // Generate chart
  const result = generateMacdVChart({
    symbol,
    timeframe,
    candles,
    displayBars,
    width: 1000,
    height: 600,
  });

  console.log(`Chart generated: ${result.width}x${result.height}, ${result.buffer.length} bytes`);

  // Save to tmp/
  if (!existsSync('tmp')) mkdirSync('tmp');
  const filename = `${symbol.replace('-', '')}-${timeframe}-macdv.png`;
  const filepath = `tmp/${filename}`;
  writeFileSync(filepath, result.buffer);
  console.log(`Saved: ${filepath}`);

  // Post to Discord if requested
  if (postToDiscord) {
    const webhookUrl = process.env.DISCORD_LIVERMORE_BOT;
    if (!webhookUrl) {
      console.error('DISCORD_LIVERMORE_BOT not set — cannot post to Discord');
      await redis.quit();
      process.exit(1);
    }

    console.log('Posting to Discord...');

    // Get current MACD-V value for the embed description
    const lastCandle = candles[candles.length - 1];
    const price = lastCandle.close;
    const age = Math.round((Date.now() - lastCandle.timestamp) / 60000);

    // Discord multipart/form-data with image attachment
    const formData = new FormData();

    const embed = {
      title: `${symbol} — MACD-V (${timeframe})`,
      description: `Price: $${price.toLocaleString()} | Data age: ${age}m`,
      color: 0x1a1a2e, // Dark theme color
      image: { url: `attachment://${filename}` },
      footer: { text: 'Generated by Perseus/Livermore' },
      timestamp: new Date().toISOString(),
    };

    const payload = JSON.stringify({ embeds: [embed] });
    formData.append('payload_json', payload);
    formData.append('files[0]', new Blob([result.buffer], { type: 'image/png' }), filename);

    const response = await fetch(webhookUrl, {
      method: 'POST',
      body: formData,
    });

    if (!response.ok) {
      const text = await response.text();
      console.error(`Discord error: ${response.status} ${text}`);
    } else {
      console.log('Posted to Discord!');
    }
  }

  await redis.quit();
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
