param(
    [string]$ImagePath,
    [string]$Title,
    [string]$Description,
    [int]$Color = 0x1a1a2e
)

$webhook = [Environment]::GetEnvironmentVariable('DISCORD_LIVERMORE_BOT', 'User')
if (-not $webhook) {
    Write-Error "DISCORD_LIVERMORE_BOT not set"
    exit 1
}

$filename = Split-Path $ImagePath -Leaf

$embed = @{
    title = $Title
    description = $Description
    color = $Color
    image = @{ url = "attachment://$filename" }
    footer = @{ text = "Generated by Perseus/Livermore" }
    timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
}

$payload = @{ embeds = @($embed) } | ConvertTo-Json -Depth 5

$boundary = [System.Guid]::NewGuid().ToString()
$LF = "`r`n"

$bodyLines = @(
    "--$boundary",
    "Content-Disposition: form-data; name=`"payload_json`"",
    "Content-Type: application/json$LF",
    $payload,
    "--$boundary",
    "Content-Disposition: form-data; name=`"files[0]`"; filename=`"$filename`"",
    "Content-Type: image/png$LF"
) -join $LF

$imageBytes = [System.IO.File]::ReadAllBytes($ImagePath)
$headerBytes = [System.Text.Encoding]::UTF8.GetBytes($bodyLines)
$footerBytes = [System.Text.Encoding]::UTF8.GetBytes("$LF--$boundary--$LF")

$body = New-Object byte[] ($headerBytes.Length + $imageBytes.Length + $footerBytes.Length)
[System.Buffer]::BlockCopy($headerBytes, 0, $body, 0, $headerBytes.Length)
[System.Buffer]::BlockCopy($imageBytes, 0, $body, $headerBytes.Length, $imageBytes.Length)
[System.Buffer]::BlockCopy($footerBytes, 0, $body, $headerBytes.Length + $imageBytes.Length, $footerBytes.Length)

Invoke-RestMethod -Uri $webhook -Method Post -ContentType "multipart/form-data; boundary=$boundary" -Body $body
Write-Host "Posted to Discord with image"
